### ISSUE TITLE
FMU simulation with file dependencies fails

### ISSUE THREAD

**Issue by tbeu** [PySimulator/PySimulator#1]
The fmu simulation of http://www.FastShare.org/download/T.fmu succeeds with official FMU checker but fails with PySimulator demonstrating three issues:

1) The output is:

```
Info: ... loading "a" from "test_v4.mat"

%s: %s
%s: %s
Model initialization failed. fmiStatus = 3
```

Thus, the error message from the FMU is not displayed.

2) File dependencies within the FMU should also be extracted.

3) It still does not simulate if the file dependencies are manually copied to the %TEMP% dir. Thus the working directory is not set as expected.

**Comment by AndreasPfeiffer** [comment]
Tried to fix the issue. Please test it with your FMU - is no more available under the link above. If the issue still remains, please provide the FMU. Thanks.

**Comment by tbeu** [comment]
T.fmu is there again. Link is only valid 31 days if not requested. Please test again.
