### ISSUE TITLE
FMUSimulator fails to load binary if it depends on other binaries

### ISSUE THREAD

**Issue by adeas31** [PySimulator/PySimulator#53]
The latest FMUs from `OpenModelica` are not working anymore because now FMU binary depends on `pthreadGC2.dll` and `libgfortran-3.dll`.

I saw that FMUSimulator creates a copy of the FMU binary in the temp folder and load it from there. In that case the dependent binaries should be copied as well.

**Comment by AndreasPfeiffer** [comment]
Please test, if the OpenModelica plugin is working again.

**Comment by adeas31** [comment]
Still not working. Error is,
{{{
Traceback (most recent call last):
  File "PySimulator.py", line 354, in openModelFile
    model = loaderplugin.getNewModel(modelName, [fileName], self.config)
  File "C:\DLR\PySimulator\PySimulator\Plugins\Simulator\FMUSimulator\FMUSimulat
or.py", line 96, in getNewModel
    return Model(modelName, modelFileName, config)
  File "C:\DLR\PySimulator\PySimulator\Plugins\Simulator\FMUSimulator\FMUSimulat
or.py", line 129, in __init__
    self.interface = FMUInterface.FMUInterface(modelFileName[0], self, loggingOn
)
  File "C:\DLR\PySimulator\PySimulator\Plugins\Simulator\FMUSimulator\FMUInterfa
ce.py", line 153, in __init__
    self._InstantiateModel()
  File "C:\DLR\PySimulator\PySimulator\Plugins\Simulator\FMUSimulator\FMUInterfa
ce.py", line 213, in _InstantiateModel
    raise FMUError.FMUError('Error when loading binary from FMU.\n' + str(e) + '
\n')
FMUError
}}}

**Comment by AndreasPfeiffer** [comment]
Please set “loggingOn=True” in the __init__ function of the class “FMUSimulator.Model” and report the error message again (maybe reported into the Information output window of PySimulator)

**Comment by adeas31** [comment]
same error. the information window says,

```
Error when loading binary from FMU.
[Error 126] The specified module could not be found
```
