### ISSUE TITLE
Missing bs4 dependency of Testing plugin not mentioned in the wiki

### ISSUE THREAD

**Issue by tbeu** [PySimulator/PySimulator#57]
@arun3688 I get a load error ```Testing plug-in could not be loaded. Error message: 'No module named bs4'```. The [Wiki](../wiki/Installation) gives no clue that non-standard module bs4 is needed by Testing plugin. It should be mentioned in the optional libraries for sake of completeness.

**Comment by arun3688** [comment]
bs4 means BeautifulSoup. It is a library in python for parsing HTML documents. It is available for python versions 2.6 + and python 3. For more details http://en.wikipedia.org/wiki/Beautiful_Soup. It should be available in the following paths /Python27/Lib/site-packages/bs4/. The default Pysimulator installation does this.

**Comment by tbeu** [comment]
Sorry, it is neither part of default Python nor default PySimulator installation. It is now fixed by 230a86e (for PySimulator).

**Comment by tbeu** [comment]
Updated [Wiki](../wiki/Installation).
