### ISSUE TITLE
FMU simulation broken

### ISSUE THREAD

**Issue by tbeu** [PySimulator/PySimulator#63]
Current master gives
 * ```FMUs 2.0 not yet supported by FMUSimulator.``` on \Examples\FMU2.0\Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_fullRobot.fmu and
 * ```No module named FMUSimulator1``` on \Examples\FMU1.0\Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_fullRobot.fmu

**Comment by AndreasPfeiffer** [comment]
I cannot reproduce the issues. Please could you try to find the issue in more detail?

**Comment by tbeu** [comment]
I can reproduce on different PC. It fails for 32-bit and 64-bit Python. It does not fail if started from Eclipse + PyDev. Please try to reproduce.

**Comment by tbeu** [comment]
Thank you. Fix confirmed.
