### ISSUE TITLE
Can PySimulator installation on win7 64bit？ Or installation on win10 32bit？ 

### ISSUE THREAD

**Issue by lovezzk** [PySimulator/PySimulator#83]
Can PySimulator installation on win7 64bit？ And I have installation on win7 64bit, but when I click the PySimulator icon which appear on the desktop after the installation , did not start any programs. What causes the failure?

one more question:
Can PySimulator installation on win10 32bit？ When do the step on  "C:\Python27\python.exe setup.py install" , cause a failure,  the error is "Name error: name 'sys_platform' is nor defined ". And the error is appear when run the file setup.py which in the package "distribute 0.6.49".

Thank you for your answer!

**Comment by tbeu** [comment]
Did you check the /wiki/Installation?

**Comment by thorade** [comment]
Wiki is here:
https://github.com/PySimulator/PySimulator/wiki/Installation

The setup.py should be updated to reflect all supported Windows versions:
https://github.com/PySimulator/PySimulator/blob/master/setup.py
Or remove that section completely, and mention the supported Python version instead:
https://docs.python.org/3.6/howto/pyporting.html#update-your-setup-py-file-to-denote-python-3-compatibility
